// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChNKSCyhYiadHC0i3A2nef031jrV5leFM',
    appId: '1:35029866995:web:641a5df8bf6c6bef995a86',
    messagingSenderId: '35029866995',
    projectId: 'minimalchadapp',
    authDomain: 'minimalchadapp.firebaseapp.com',
    storageBucket: 'minimalchadapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClhhRtWPEfbp_pM3gLpENzO3zIHN1w-jU',
    appId: '1:35029866995:android:c09aa523471a8d85995a86',
    messagingSenderId: '35029866995',
    projectId: 'minimalchadapp',
    storageBucket: 'minimalchadapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBojUm2CC6jqo7skFoCsYObhJXv0HwEF9w',
    appId: '1:35029866995:ios:1a26edaf3aea7997995a86',
    messagingSenderId: '35029866995',
    projectId: 'minimalchadapp',
    storageBucket: 'minimalchadapp.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBojUm2CC6jqo7skFoCsYObhJXv0HwEF9w',
    appId: '1:35029866995:ios:1a26edaf3aea7997995a86',
    messagingSenderId: '35029866995',
    projectId: 'minimalchadapp',
    storageBucket: 'minimalchadapp.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChNKSCyhYiadHC0i3A2nef031jrV5leFM',
    appId: '1:35029866995:web:d05da0b2eb8ac9e7995a86',
    messagingSenderId: '35029866995',
    projectId: 'minimalchadapp',
    authDomain: 'minimalchadapp.firebaseapp.com',
    storageBucket: 'minimalchadapp.firebasestorage.app',
  );
}
